/* eslint-disable react-hooks/exhaustive-deps */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/model/iot2.glb -o src/components/model/House.tsx -t -k -T -j 
Files: public/model/iot2.glb [78.49MB] > iot2-transformed.glb [1.96MB] (98%)
*/

import * as THREE from "three";
import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import TWEEN, { Tween } from "@tweenjs/tween.js";
import { RainModel } from "./Rain";
import { randInt } from "three/src/math/MathUtils.js";
import { Luffy } from "./Objects/Luffy";
import { Goku } from "./Objects/Goku";
import { Robber } from "./Objects/Robber";
import { RobberDuck } from "./Objects/RobberDuck";

type GLTFResult = GLTF & {
  nodes: {
    Cube001_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube002_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube003__handle_Iron_brushed_0: THREE.Mesh;
    Cube021__door_shade_Wood_4_0: THREE.Mesh;
    Cube023_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube025_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube026_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube027_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube028_Multicoated_glass_0: THREE.Mesh;
    Cube029_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube030_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube031_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube032_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube033_Multicoated_glass_0: THREE.Mesh;
    Cube034_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube035_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube036_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube037_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube038_Multicoated_glass_0: THREE.Mesh;
    Cube039_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube040_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube041_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube042_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube044_hand_railBrushed_stainless_steel_0: THREE.Mesh;
    Cube045__floor_Ceramic_Black_Tiles__0: THREE.Mesh;
    Cube045_shades_brown_0: THREE.Mesh;
    Cube046__floor_Ceramic_Black_Tiles__0: THREE.Mesh;
    Cube047__floor_Ceramic_Black_Tiles__0: THREE.Mesh;
    Cube049__door_shade_Wood_4_0: THREE.Mesh;
    Cube050__door_shade_Wood_4_0_1: THREE.Mesh;
    Cube050__door_shade_Wood_4_0_2: THREE.Mesh;
    // Cube050__door_shade_Wood_4_0_1: THREE.Mesh
    // Cube050__door_shade_Wood_4_0_2: THREE.Mesh
    Cube051__handle_Iron_brushed_0: THREE.Mesh;
    Cube052__door_shade_Wood_4_0: THREE.Mesh;
    Cube052_Multicoated_glass_0: THREE.Mesh;
    Cube053_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube054_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube055__handle_Iron_brushed_0: THREE.Mesh;
    Cube057_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube058_Multicoated_glass_0: THREE.Mesh;
    Cube059_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube060_Multicoated_glass_0: THREE.Mesh;
    Cube061_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube062_Multicoated_glass_0: THREE.Mesh;
    Cube063_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube064_Multicoated_glass_0: THREE.Mesh;
    Cube066_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube067_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube068_Multicoated_glass_0: THREE.Mesh;
    Cube068_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube069_Multicoated_glass_0: THREE.Mesh;
    Cube069_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube070_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube071_Multicoated_glass_0: THREE.Mesh;
    Cube071_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube072_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube073_Multicoated_glass_0: THREE.Mesh;
    Cube073_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube075_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube076_Multicoated_glass_0: THREE.Mesh;
    Cube076_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube077_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube078_Multicoated_glass_0: THREE.Mesh;
    Cube078_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube079_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Cube080_Multicoated_glass_0: THREE.Mesh;
    Cube080_window_Brushed__Dark_Metal_0: THREE.Mesh;
    piller_1_shades_brown_0: THREE.Mesh;
    Plane_landscape_tiles_0: THREE.Mesh;
    Plane008_shades_brown_0: THREE.Mesh;
    Plane010_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Plane011_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Plane012_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Plane013_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Plane014_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Plane015_window_Brushed__Dark_Metal_0: THREE.Mesh;
    Plane016_window_Brushed__Dark_Metal_0: THREE.Mesh;
    shade_01_shades_brown_0: THREE.Mesh;
    shade_02_shades_brown_0: THREE.Mesh;
    Object_2: THREE.Mesh;
    Plane008_wall_paint_0: THREE.Mesh;
  };
  materials: {
    window_Brushed__Dark_Metal: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    floor_Ceramic_Black_Tiles: THREE.MeshStandardMaterial;
    landscape_tiles: THREE.MeshStandardMaterial;
    Canopy3initialShadingGroup: THREE.MeshStandardMaterial;
    wall_paint: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;
interface HouseProp {
  doorOpen?: boolean;
  canopyOpen?: boolean;
  doorDetect?: boolean;
}
export function House(props: JSX.IntrinsicElements["group"] & HouseProp) {
  const { nodes, materials } = useGLTF("/iot2-transformed.glb") as GLTFResult;
  const doorRef = useRef<THREE.Group>(null);
  useEffect(() => {
    if (doorRef.current) {
      const startRotation = new THREE.Euler().fromArray(
        doorRef?.current?.rotation.toArray() as any,
      ); // Initial rotation
      const endRotation = new THREE.Euler().fromArray(
        props.doorOpen ? [-Math.PI / 2, 0, Math.PI / 3] : [-Math.PI / 2, 0, 0],
      ); // Desired rotation

      // Set up animation
      const tween = new TWEEN.Tween({
        x: startRotation.x,
        y: startRotation.y,
        z: startRotation.z,
      })
        .to({ x: endRotation.x, y: endRotation.y, z: endRotation.z }, 1000) // Animation duration (milliseconds)
        .onUpdate(function (value) {
          if (doorRef.current) {
            doorRef.current.rotation.set(value.x, value.y, value.z); // Update group rotation in each frame
          }
        })
        .start() // Start the animation
        .onComplete(() => {
          tween.stop(); // Stop the animation when completed
        });

      // Animation loop
      // @ts-ignore
      function animate() {
        console.log("in animated");
        if (tween.isPlaying()) {
          requestAnimationFrame(animate);
          TWEEN.update(); // Update animations
        }
      }
      animate();
    }
  }, [props.doorOpen, doorRef.current]);
  const canopyRef = useRef<THREE.Group>(null);

  useEffect(() => {
    if (canopyRef.current) {
      const startScale = canopyRef.current.scale.clone(); // Initial scale
      const endScale = props.canopyOpen
        ? new THREE.Vector3(0.534, 0.83, 0.302)
        : new THREE.Vector3(0.534, 0.15, 0.302); // Desired scale

      // Set up animation
      const tween = new TWEEN.Tween({
        x: startScale.x,
        y: startScale.y,
        z: startScale.z,
      })
        .to({ x: endScale.x, y: endScale.y, z: endScale.z }, 1000) // Animation duration (milliseconds)
        .onUpdate(function (value) {
          if (canopyRef.current) {
            canopyRef.current.scale.set(value.x, value.y, value.z); // Update group scale in each frame
          }
        })
        .start() // Start the animation
        .onComplete(() => {
          tween.stop(); // Stop the animation when completed
        });

      // Animation loop
      //@ts-ignore
      function animate() {
        if (tween.isPlaying()) {
          requestAnimationFrame(animate);
          TWEEN.update(); // Update animations
        }
      }
      animate();
    }
  }, [props.canopyOpen, canopyRef.current]);

  const DootObject = useMemo(() => {
    if (props.doorDetect) {
      const rand = randInt(1, 4);
      switch (rand) {
        case 1:
          return <Luffy position={[0, 0.7, 0]} scale={[0.8, 0.8, 0.5]}></Luffy>;
        case 2:
          return <Goku position={[0, 0.55, 0]} scale={[0.8, 0.8, 0.8]} />;
        case 3:
          return <Robber position={[0, 1, 0]} scale={[0.4, 0.4, 0.4]} />;
        case 4:
          return <RobberDuck position={[0, 1.6, 0]} scale={[0.4, 0.4, 0.4]} />;
        default:
          return <RobberDuck position={[0, 1.6, 0]} scale={[0.4, 0.4, 0.4]} />;
      }
    } else return null;
  }, [props.doorDetect]);
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube001_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube001_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        position={[-1.995, 7.875, -4.766]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube002_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube002_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        position={[-2.07, 8.088, -4.676]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube003__handle_Iron_brushed_0"
        geometry={nodes.Cube003__handle_Iron_brushed_0.geometry}
        material={materials.PaletteMaterial001}
        position={[-2.032, 8.054, -4.313]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube021__door_shade_Wood_4_0"
        geometry={nodes.Cube021__door_shade_Wood_4_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube023_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube023_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube025_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube025_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube026_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube026_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube027_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube027_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
      />
      <mesh
        name="Cube028_Multicoated_glass_0"
        geometry={nodes.Cube028_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube029_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube029_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube030_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube030_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube031_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube031_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube032_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube032_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube033_Multicoated_glass_0"
        geometry={nodes.Cube033_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube034_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube034_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube035_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube035_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube036_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube036_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Cube037_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube037_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Cube038_Multicoated_glass_0"
        geometry={nodes.Cube038_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube039_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube039_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube040_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube040_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube041_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube041_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Cube042_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube042_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Cube044_hand_railBrushed_stainless_steel_0"
        geometry={nodes.Cube044_hand_railBrushed_stainless_steel_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube045__floor_Ceramic_Black_Tiles__0"
        geometry={nodes.Cube045__floor_Ceramic_Black_Tiles__0.geometry}
        material={materials.floor_Ceramic_Black_Tiles}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube045_shades_brown_0"
        geometry={nodes.Cube045_shades_brown_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube046__floor_Ceramic_Black_Tiles__0"
        geometry={nodes.Cube046__floor_Ceramic_Black_Tiles__0.geometry}
        material={materials.floor_Ceramic_Black_Tiles}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube047__floor_Ceramic_Black_Tiles__0"
        geometry={nodes.Cube047__floor_Ceramic_Black_Tiles__0.geometry}
        material={materials.floor_Ceramic_Black_Tiles}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube049__door_shade_Wood_4_0"
        geometry={nodes.Cube049__door_shade_Wood_4_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group
        name="Cube050__door_shade_Wood_4_0"
        position={[0.499, 1.793, -0.722]}
        rotation={[-Math.PI / 2, 0, 0]}
        ref={doorRef}
      >
        <mesh
          name="Cube050__door_shade_Wood_4_0_1"
          geometry={nodes.Cube050__door_shade_Wood_4_0_1.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          name="Cube050__door_shade_Wood_4_0_2"
          geometry={nodes.Cube050__door_shade_Wood_4_0_2.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      {/* <mesh name="Cube051__handle_Iron_brushed_0" geometry={nodes.Cube051__handle_Iron_brushed_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} /> */}
      <mesh
        name="Cube052__door_shade_Wood_4_0"
        geometry={nodes.Cube052__door_shade_Wood_4_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube052_Multicoated_glass_0"
        geometry={nodes.Cube052_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube053_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube053_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube054_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube054_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube055__handle_Iron_brushed_0"
        geometry={nodes.Cube055__handle_Iron_brushed_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube057_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube057_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube058_Multicoated_glass_0"
        geometry={nodes.Cube058_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube059_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube059_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube060_Multicoated_glass_0"
        geometry={nodes.Cube060_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube061_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube061_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube062_Multicoated_glass_0"
        geometry={nodes.Cube062_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube063_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube063_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube064_Multicoated_glass_0"
        geometry={nodes.Cube064_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube066_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube066_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube067_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube067_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube068_Multicoated_glass_0"
        geometry={nodes.Cube068_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube068_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube068_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube069_Multicoated_glass_0"
        geometry={nodes.Cube069_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube069_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube069_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Cube070_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube070_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube071_Multicoated_glass_0"
        geometry={nodes.Cube071_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube071_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube071_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube072_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube072_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube073_Multicoated_glass_0"
        geometry={nodes.Cube073_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube073_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube073_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="Cube075_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube075_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube076_Multicoated_glass_0"
        geometry={nodes.Cube076_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube076_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube076_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube077_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube077_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube078_Multicoated_glass_0"
        geometry={nodes.Cube078_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube078_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube078_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube079_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube079_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube080_Multicoated_glass_0"
        geometry={nodes.Cube080_Multicoated_glass_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="Cube080_window_Brushed__Dark_Metal_0"
        geometry={nodes.Cube080_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        name="piller_1_shades_brown_0"
        geometry={nodes.piller_1_shades_brown_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Plane_landscape_tiles_0"
        geometry={nodes.Plane_landscape_tiles_0.geometry}
        material={materials.landscape_tiles}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Plane008_shades_brown_0"
        geometry={nodes.Plane008_shades_brown_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Plane010_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane010_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
      />
      <mesh
        name="Plane011_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane011_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
      />
      <mesh
        name="Plane012_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane012_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
      />
      <mesh
        name="Plane013_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane013_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        name="Plane014_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane014_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        name="Plane015_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane015_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        name="Plane016_window_Brushed__Dark_Metal_0"
        geometry={nodes.Plane016_window_Brushed__Dark_Metal_0.geometry}
        material={materials.window_Brushed__Dark_Metal}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        name="shade_01_shades_brown_0"
        geometry={nodes.shade_01_shades_brown_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="shade_02_shades_brown_0"
        geometry={nodes.shade_02_shades_brown_0.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Object_2"
              //@ts-ignore
        ref={canopyRef}
        geometry={nodes.Object_2.geometry}
        material={materials.Canopy3initialShadingGroup}
        position={[1.736, 7.193, -0.135]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.534, 0.83, 0.302]}
      />
      <mesh
        name="Plane008_wall_paint_0"
        geometry={nodes.Plane008_wall_paint_0.geometry}
        material={materials.wall_paint}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {props?.canopyOpen && (
        <RainModel position={[0, -20, -5]} scale={[0.15, 0.15, 0.15]} />
      )}
      {DootObject}
    </group>
  );
}

useGLTF.preload("/iot2-transformed.glb");
