/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/model/rain.glb -o src/components/model/Rain.tsx -t -k -T 
Files: public/model/rain.glb [290.5KB] > rain-transformed.glb [68.64KB] (76%)
Author: Paxar095 (https://sketchfab.com/paxar095)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rain-ef6447b531d04a9997e709aef7fcabf2
Title: Rain
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Box017_02_-_Default_0']: THREE.Mesh
    ['Box018_02_-_Default_0']: THREE.Mesh
    ['Box020_02_-_Default��_0']: THREE.Mesh
    ['Box021_02_-_Default_0']: THREE.Mesh
    ['Box022_02_-_Default_0']: THREE.Mesh
    ['Box023_02_-_Default��_0']: THREE.Mesh
    ['Box024_02_-_Default_0']: THREE.Mesh
    ['Box025_02_-_Default��_0']: THREE.Mesh
    ['Box026_02_-_Default��_0']: THREE.Mesh
    ['Box027_02_-_Default��_0']: THREE.Mesh
    ['Box028_02_-_Default��_0']: THREE.Mesh
    ['Box029_13_-_Default_0']: THREE.Mesh
    ['Box030_13_-_Default_0']: THREE.Mesh
    ['Plane001_16_-_Default_0']: THREE.Mesh
    ['Plane002_16_-_Default_0']: THREE.Mesh
    ['Plane003_16_-_Default_0']: THREE.Mesh
    ['Plane004_16_-_Default_0']: THREE.Mesh
    ['Plane005_16_-_Default_0']: THREE.Mesh
    ['Plane006_16_-_Default_0']: THREE.Mesh
    ['Plane007_16_-_Default_0']: THREE.Mesh
    ['Plane008_16_-_Default_0']: THREE.Mesh
    ['Plane009_16_-_Default_0']: THREE.Mesh
    ['Plane010_16_-_Default_0']: THREE.Mesh
    ['Plane011_16_-_Default_0']: THREE.Mesh
    ['Plane012_16_-_Default_0']: THREE.Mesh
    ['Plane013_16_-_Default_0']: THREE.Mesh
    ['Plane014_16_-_Default_0']: THREE.Mesh
    ['Plane015_16_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['02_-_Default']: THREE.MeshStandardMaterial
    ['02_-_Default_1']: THREE.MeshStandardMaterial
    ['13_-_Default']: THREE.MeshStandardMaterial
    ['16_-_Default']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Take 001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function RainModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/rain-transformed.glb') as GLTFResult
  const { actions, } = useAnimations<any>(animations, group)
  useEffect(()=>{
    console.log(actions);
    actions?.["Take 001"]?.play()
    //TODO play animations?.[0] infinitely until unmount
  },[actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="rain" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Box017" position={[-35.314, -74.909, 212.071]} rotation={[0, 0, -1.484]} scale={0.506}>
            <mesh name="Box017_02_-_Default_0" geometry={nodes['Box017_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group>
          <group name="Box018" position={[-5.604, 0.777, 230.386]} rotation={[0.008, -0.087, -1.483]} scale={1.382}>
            <mesh name="Box018_02_-_Default_0" geometry={nodes['Box018_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group>
          <group name="Box020" position={[94.042, 2.332, 245.517]} rotation={[0, 0, -1.484]} scale={0.39}>
            <mesh name="Box020_02_-_Default��_0" geometry={nodes['Box020_02_-_Default��_0'].geometry} material={materials['02_-_Default_1']} />
          </group>
          <group name="Box021" position={[-14.077, 64.825, 239.498]} rotation={[0, 0, -1.484]} scale={0.521}>
            <mesh name="Box021_02_-_Default_0" geometry={nodes['Box021_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group>
          <group name="Box022" position={[41.708, -70.434, 209.781]} rotation={[0, 0, Math.PI / 2]} scale={0.707}>
            <mesh name="Box022_02_-_Default_0" geometry={nodes['Box022_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group>
          <group name="Box023" position={[-57.454, -15.756, 255.2]} rotation={[0, 0, -1.484]} scale={0.39}>
            <mesh name="Box023_02_-_Default��_0" geometry={nodes['Box023_02_-_Default��_0'].geometry} material={materials['02_-_Default_1']} />
          </group>
          <group name="Box024" position={[61.705, -23.791, 240.284]} rotation={[3.055, 0.008, -1.658]} scale={0.261}>
            <mesh name="Box024_02_-_Default_0" geometry={nodes['Box024_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          </group>
          <group name="Box025" position={[5.1, -39.247, 235.53]} rotation={[0, 0, -1.484]} scale={0.521}>
            <mesh name="Box025_02_-_Default��_0" geometry={nodes['Box025_02_-_Default��_0'].geometry} material={materials['02_-_Default_1']} />
          </group>
          <group name="Box026" position={[70.031, 50.68, 253.427]} rotation={[3.077, -0.075, -1.576]} scale={[0.581, 0.581, 0.506]}>
            <mesh name="Box026_02_-_Default��_0" geometry={nodes['Box026_02_-_Default��_0'].geometry} material={materials['02_-_Default_1']} />
          </group>
          <group name="Box027" position={[-96.111, -59.783, 240.284]} rotation={[0.088, 0.008, -1.658]} scale={0.261}>
            <mesh name="Box027_02_-_Default��_0" geometry={nodes['Box027_02_-_Default��_0'].geometry} material={materials['02_-_Default_1']} />
          </group>
          <group name="Box028" position={[-82.39, 44.507, 233.271]} rotation={[0, 0, -1.484]} scale={0.362}>
            <mesh name="Box028_02_-_Default��_0" geometry={nodes['Box028_02_-_Default��_0'].geometry} material={materials['02_-_Default_1']} />
          </group>
          <group name="Box029" position={[-27.948, -13.706, 227.46]} rotation={[0.087, 0, 0]} scale={0.025}>
            <group name="Object_28" position={[0, 0, -0.392]}>
              <mesh name="Box029_13_-_Default_0" geometry={nodes['Box029_13_-_Default_0'].geometry} material={materials['13_-_Default']} />
            </group>
          </group>
          <group name="Box030" position={[-1.546, 32.353, 227.46]} rotation={[-0.011, -0.089, 1.324]} scale={0.025}>
            <group name="Object_31" position={[0, 0, -0.392]}>
              <mesh name="Box030_13_-_Default_0" geometry={nodes['Box030_13_-_Default_0'].geometry} material={materials['13_-_Default']} />
            </group>
          </group>
          <group name="Plane001" position={[-41.64, -29.682, 189.936]} scale={0.553}>
            <group name="Object_34" position={[0, 0, -7.102]}>
              <mesh name="Plane001_16_-_Default_0" geometry={nodes['Plane001_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane002" position={[-3.743, 3.479, 151.178]} scale={0.874}>
            <group name="Object_37" position={[0, 0, -7.102]}>
              <mesh name="Plane002_16_-_Default_0" geometry={nodes['Plane002_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane003" position={[26.075, -22.578, 189.936]} scale={0.553}>
            <group name="Object_40" position={[0, 0, -7.102]}>
              <mesh name="Plane003_16_-_Default_0" geometry={nodes['Plane003_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane004" position={[52.081, 3.236, 227.46]} scale={0.087}>
            <group name="Object_43" position={[0, 0, -7.102]}>
              <mesh name="Plane004_16_-_Default_0" geometry={nodes['Plane004_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane005" position={[21.97, 15.286, 227.46]} scale={0.087}>
            <group name="Object_46" position={[0, 0, -7.102]}>
              <mesh name="Plane005_16_-_Default_0" geometry={nodes['Plane005_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane006" position={[53.896, 38.917, 189.936]} scale={0.553}>
            <group name="Object_49" position={[0, 0, -7.102]}>
              <mesh name="Plane006_16_-_Default_0" geometry={nodes['Plane006_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane007" position={[-45.329, 25.829, 227.46]} scale={0.087}>
            <group name="Object_52" position={[0, 0, -7.102]}>
              <mesh name="Plane007_16_-_Default_0" geometry={nodes['Plane007_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane008" position={[-88.613, 43.056, 227.46]} scale={0.087}>
            <group name="Object_55" position={[0, 0, -7.102]}>
              <mesh name="Plane008_16_-_Default_0" geometry={nodes['Plane008_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane009" position={[-29.138, -73.944, 227.46]} scale={0.087}>
            <group name="Object_58" position={[0, 0, -7.102]}>
              <mesh name="Plane009_16_-_Default_0" geometry={nodes['Plane009_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane010" position={[60.82, -80.959, 117.467]} scale={1.019}>
            <group name="Object_61" position={[0, 0, -7.102]}>
              <mesh name="Plane010_16_-_Default_0" geometry={nodes['Plane010_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane011" position={[23.838, -61.692, 117.467]} scale={1.019}>
            <group name="Object_64" position={[0, 0, -7.102]}>
              <mesh name="Plane011_16_-_Default_0" geometry={nodes['Plane011_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane012" position={[73.988, 49.857, 227.46]} scale={0.087}>
            <group name="Object_67" position={[0, 0, -7.102]}>
              <mesh name="Plane012_16_-_Default_0" geometry={nodes['Plane012_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane013" position={[23.03, 11.901, 151.178]} scale={0.874}>
            <group name="Object_70" position={[0, 0, -7.102]}>
              <mesh name="Plane013_16_-_Default_0" geometry={nodes['Plane013_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane014" position={[-67.649, -9.197, 151.178]} scale={0.874}>
            <group name="Object_73" position={[0, 0, -7.102]}>
              <mesh name="Plane014_16_-_Default_0" geometry={nodes['Plane014_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
          <group name="Plane015" position={[42.46, 6.658, 117.467]} scale={1.019}>
            <group name="Object_76" position={[0, 0, -7.102]}>
              <mesh name="Plane015_16_-_Default_0" geometry={nodes['Plane015_16_-_Default_0'].geometry} material={materials['16_-_Default']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rain-transformed.glb')
