/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/model/object/cute_fox.glb -o src/components/model/Objects/Fox.tsx -t -k -T 
Files: public/model/object/cute_fox.glb [6.48MB] > cute_fox-transformed.glb [297.19KB] (95%)
Author: eexy (https://sketchfab.com/eexy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-fox-fad88d036f764cceb3938549ca446c89
Title: Cute Fox
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
    Object_25: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Fox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cute_fox-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cute_fox-transformed.glb')
