/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/model/object/luffy.glb -o src/components/model/Luffy.tsx -t -k -T 
Files: public/model/object/luffy.glb [3.12MB] > luffy-transformed.glb [558.5KB] (82%)
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monkey-d-luffy-3d9fb8bd86854aa69ee6f69fcbeaca51
Title: Monkey D. Luffy
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    LuffyD: THREE.MeshStandardMaterial
    lambert4: THREE.MeshStandardMaterial
  }
}

type ActionName = 'mixamo.com' | 'jumpDown' | 'punch' | 'run' | 'standing' | 'strafeLeft' | 'strafeRight' | 'walk' | 'wave'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Luffy(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/luffy-transformed.glb') as GLTFResult
  const { actions } = useAnimations<any>(animations, group)
  useEffect(()=>{
    actions?.["wave"]?.play()
  },[actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.LuffyD} skeleton={nodes.Object_7.skeleton} scale={0.015} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.lambert4} skeleton={nodes.Object_8.skeleton} scale={0.015} />
      </group>
    </group>
  )
}

useGLTF.preload('/luffy-transformed.glb')
