/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/model/object/shark_boi.glb -o src/components/model/Objects/Shark.tsx -t -k -T 
Files: public/model/object/shark_boi.glb [8.78MB] > shark_boi-transformed.glb [1.68MB] (81%)
Author: epilogueronin (https://sketchfab.com/epilogueronin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shark-boi-dc70dab09c104e8ba2adaf089c6c1db2
Title: Shark boi
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Eyes_low_eyes_0: THREE.Mesh
    LowerTeeth_low_teeth_0: THREE.Mesh
    swingring_low_waterring_0: THREE.Mesh
    sandplane_sand_mat_0: THREE.Mesh
    Object_38: THREE.SkinnedMesh
    Object_40: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    eyes: THREE.MeshStandardMaterial
    teeth: THREE.MeshStandardMaterial
    waterring: THREE.MeshStandardMaterial
    sand_mat: THREE.MeshStandardMaterial
    main_body: THREE.MeshStandardMaterial
    tongue: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh'] | JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['bone']>>

export function Shark(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shark_boi-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <mesh name="Eyes_low_eyes_0" geometry={nodes.Eyes_low_eyes_0.geometry} material={materials.eyes} position={[0, 0, 0]} rotation={[0, -0.009, 0.01]} scale={0.01} />
      <mesh name="LowerTeeth_low_teeth_0" geometry={nodes.LowerTeeth_low_teeth_0.geometry} material={materials.teeth} position={[0, 0, 0]} rotation={[0, -0.009, 0.01]} scale={0.01} />
      <mesh name="swingring_low_waterring_0" geometry={nodes.swingring_low_waterring_0.geometry} material={materials.waterring} position={[0, 0.012, 0]} rotation={[0.049, 0, 0]} scale={0.01} />
      <mesh name="sandplane_sand_mat_0" geometry={nodes.sandplane_sand_mat_0.geometry} material={materials.sand_mat} scale={0.026} />
      <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.main_body} skeleton={nodes.Object_38.skeleton} scale={0.01} />
      <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.tongue} skeleton={nodes.Object_40.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/shark_boi-transformed.glb')
